// <auto-generated />
using BookStore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookStore.API.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    [Migration("20220214103649_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("BookStore.API.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Let's fight for our kingdom.",
                            Title = "Prince's Legacy"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The Moon is it's greatest enemy.",
                            Title = "The Cursed Wolf"
                        },
                        new
                        {
                            Id = 3,
                            Description = "We all love it! Of course!",
                            Title = "C#"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The Killer Curse!",
                            Title = "Avada Kedavra"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Programming language, and animal.",
                            Title = "Python"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
